#!/usr/bin/env python3
"""Generate ssign pipeline summary report (HTML + text).

Summarizes: genome count, protein count, SS system counts, substrate counts,
annotation tool coverage, and key parameters.
"""

import argparse
import logging
import os
from collections import Counter

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


def generate_text_report(master_csvs, enrichment_file, output_path):
    """Generate plain text summary report."""
    # Load and combine all master CSVs
    dfs = []
    for f in master_csvs:
        try:
            dfs.append(pd.read_csv(f))
        except Exception as e:
            logger.warning(f"Could not read {f}: {e}")

    if not dfs:
        with open(output_path, "w") as f:
            f.write("ssign Report\n============\nNo results to report.\n")
        return

    df = pd.concat(dfs, ignore_index=True)

    lines = [
        "=" * 60,
        "ssign — Secretion-system Identification for Gram Negatives",
        "=" * 60,
        "",
        f"Total genomes analyzed: {df['sample_id'].nunique() if 'sample_id' in df.columns else 'N/A'}",
        f"Total substrate candidates: {len(df)}",
        "",
    ]

    # SS type distribution
    if "nearby_ss_types" in df.columns:
        ss_counts = Counter()
        for val in df["nearby_ss_types"].dropna():
            for ss in str(val).split(","):
                ss = ss.strip()
                if ss:
                    ss_counts[ss] += 1

        lines.append("Substrates per secretion system type:")
        for ss, count in ss_counts.most_common():
            lines.append(f"  {ss}: {count}")
        lines.append("")

    # Tool coverage
    tool_cols = [
        c
        for c in df.columns
        if c.startswith(
            ("blastp_", "interpro_", "pfam_", "pdb_", "ecod70_", "signalp_")
        )
    ]
    if tool_cols:
        lines.append("Annotation tool coverage:")
        for col in sorted(tool_cols):
            n_hits = df[col].notna().sum()
            lines.append(
                f"  {col}: {n_hits}/{len(df)} ({100 * n_hits / max(len(df), 1):.1f}%)"
            )
        lines.append("")

    # Enrichment summary
    if enrichment_file and os.path.exists(enrichment_file):
        lines.append("Enrichment results:")
        with open(enrichment_file) as f:
            lines.append(f.read())

    lines.append("=" * 60)

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    logger.info(f"Wrote text report to {output_path}")


def generate_html_report(master_csvs, enrichment_file, output_path):
    """Generate HTML summary report."""
    # Simple HTML wrapping the text report
    text_path = output_path.replace(".html", ".txt")
    if os.path.exists(text_path):
        with open(text_path) as f:
            text_content = f.read()
    else:
        text_content = "No results."

    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>ssign Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Tahoma, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        pre {{ background: #f8f9fa; padding: 20px; border-radius: 5px; overflow-x: auto; }}
        .footer {{ color: #7f8c8d; font-size: 0.85em; margin-top: 40px; }}
    </style>
</head>
<body>
    <h1>ssign Report</h1>
    <p>Secretion-system Identification for Gram Negatives</p>
    <pre>{text_content}</pre>
    <div class="footer">
        <p>Generated by ssign pipeline</p>
    </div>
</body>
</html>"""

    with open(output_path, "w") as f:
        f.write(html)

    logger.info(f"Wrote HTML report to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Generate ssign report")
    parser.add_argument("--master-csvs", nargs="+", required=True)
    parser.add_argument("--enrichment", default="")
    parser.add_argument("--out-html", required=True)
    parser.add_argument("--out-txt", required=True)
    args = parser.parse_args()

    generate_text_report(args.master_csvs, args.enrichment, args.out_txt)
    generate_html_report(args.master_csvs, args.enrichment, args.out_html)


if __name__ == "__main__":
    main()
