"""Tests for validate_macsyfinder_systems.py.

Three layers of behaviour:

1. parse_sys_id() — model_fqn → sys_id regex → identity fallback chain.
2. parse_macsyfinder_results() — TSV reader that tolerates header comments,
   blank lines, sample-prefixed filenames, and missing files.
3. main() — wholeness threshold, excluded-systems filter, two-file output
   (system summary + component detail).
"""

import os
import sys

import pytest


from _helpers import read_tsv_rows, run_script_main  # noqa: E402
from validate_macsyfinder_systems import (  # noqa: E402
    main as validate_main,
)
from validate_macsyfinder_systems import (
    parse_macsyfinder_results,
    parse_sys_id,
)

# ---------------------------------------------------------------------------
# parse_sys_id — model_fqn / double-underscore / regex / identity fallback
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "sys_id, model_fqn, expected",
    [
        # 1. model_fqn wins when provided
        ("anything", "TXSScan/bacteria/diderm/T5aSS", "T5aSS"),
        ("anything", "TXSScan/bacteria/diderm/T6SSi", "T6SSi"),
        ("anything", "TXSScan/foo/bar/Flagellum", "Flagellum"),
        ("anything", "TXSScan/bacteria/diderm/T5aSS/", "T5aSS"),  # trailing slash tolerated
        # 2. Double-underscore fallback
        ("contigA__T1SS", "", "T1SS"),
        # 3. Regex match for SS-type substrings
        ("contig_X_T2SS_1", "", "T2SS"),
        ("scaffold-7_T6SSi_2", "", "T6SSi"),
        ("rep1_Flagellum_3", "", "Flagellum"),
        ("rep1_pT4SSt_1", "", "pT4SSt"),
        # 4. Identity fallback when no pattern matches
        ("totally_opaque_id", "", "totally_opaque_id"),
    ],
)
def test_parse_sys_id(sys_id, model_fqn, expected):
    assert parse_sys_id(sys_id, model_fqn) == expected


# ---------------------------------------------------------------------------
# parse_macsyfinder_results — TSV reader for best_solution.tsv
# ---------------------------------------------------------------------------


_BEST_SOLUTION_HEADER = "sys_id\tmodel_fqn\thit_id\tgene_name\thit_status\tsys_wholeness"


def _write_best_solution(path, rows, *, header=True, prefix_comments=True):
    """Build a best_solution.tsv with realistic comment headers + data rows."""
    with open(path, "w") as f:
        if prefix_comments:
            f.write("# This file is generated by MacSyFinder\n")
            f.write("# version: 2.1.4\n")
            f.write("\n")
        if header:
            f.write(_BEST_SOLUTION_HEADER + "\n")
        for r in rows:
            f.write(
                "\t".join(
                    str(r.get(k, ""))
                    for k in [
                        "sys_id",
                        "model_fqn",
                        "hit_id",
                        "gene_name",
                        "hit_status",
                        "sys_wholeness",
                    ]
                )
                + "\n"
            )


def _component(sys_id, hit_id, gene_name="g", *, model_fqn="", wholeness=1.0, hit_status="mandatory"):
    return {
        "sys_id": sys_id,
        "model_fqn": model_fqn,
        "hit_id": hit_id,
        "gene_name": gene_name,
        "hit_status": hit_status,
        "sys_wholeness": wholeness,
    }


class TestParseMacsyfinderResults:
    def test_groups_components_by_sys_id(self, tmp_dir):
        path = os.path.join(tmp_dir, "best_solution.tsv")
        _write_best_solution(
            path,
            [
                _component("contig_T2SS_1", "GENE_A", "gspD"),
                _component("contig_T2SS_1", "GENE_B", "gspE"),
                _component("contig_T1SS_1", "GENE_C", "tolC"),
            ],
        )
        systems = parse_macsyfinder_results(tmp_dir)
        by_id = {s["sys_id"]: s for s in systems}
        assert len(by_id["contig_T2SS_1"]["components"]) == 2
        assert len(by_id["contig_T1SS_1"]["components"]) == 1

    def test_uses_model_fqn_when_present(self, tmp_dir):
        path = os.path.join(tmp_dir, "best_solution.tsv")
        _write_best_solution(
            path,
            [
                _component("opaque_id", "GENE_A", model_fqn="TXSScan/bacteria/diderm/T5aSS"),
            ],
        )
        systems = parse_macsyfinder_results(tmp_dir)
        assert systems[0]["ss_type"] == "T5aSS"

    def test_invalid_wholeness_falls_back_to_zero(self, tmp_dir):
        path = os.path.join(tmp_dir, "best_solution.tsv")
        _write_best_solution(
            path,
            [
                _component("contig_T2SS_1", "GENE_A", wholeness="not-a-number"),
            ],
        )
        systems = parse_macsyfinder_results(tmp_dir)
        assert systems[0]["wholeness"] == 0.0

    def test_skips_blank_and_comment_lines(self, tmp_dir):
        # The fixture writer already prepends comments + blank line; verify the
        # parser still picks up the data rows correctly.
        path = os.path.join(tmp_dir, "best_solution.tsv")
        _write_best_solution(path, [_component("contig_T2SS_1", "GENE_A")])
        systems = parse_macsyfinder_results(tmp_dir)
        assert len(systems) == 1

    # Note: a `if not sys_id: continue` guard exists in parse_macsyfinder_results
    # but is effectively unreachable. The parser does `line.strip()` on every
    # row first, which collapses leading empty TSV fields and shifts the
    # remaining columns left — so a row with an empty sys_id never surfaces
    # as `sys_id == ""` in the dict. Real MacSyFinder output never has an
    # empty sys_id, so this is a defensive-but-dead branch. Not testing it.

    def test_sample_prefixed_filename_resolved(self, tmp_dir):
        # Some MacSyFinder runs name the output {sample}_best_solution.tsv —
        # parser falls back to a directory glob if best_solution.tsv is absent.
        path = os.path.join(tmp_dir, "mysample_best_solution.tsv")
        _write_best_solution(path, [_component("contig_T2SS_1", "GENE_A")])
        systems = parse_macsyfinder_results(tmp_dir)
        assert len(systems) == 1

    def test_missing_file_returns_empty_list(self, tmp_dir):
        # No best_solution.tsv at all → empty list (logged warning, no crash)
        assert parse_macsyfinder_results(tmp_dir) == []

    def test_empty_file_returns_empty_list(self, tmp_dir):
        path = os.path.join(tmp_dir, "best_solution.tsv")
        _write_best_solution(path, [], header=False)
        assert parse_macsyfinder_results(tmp_dir) == []


# ---------------------------------------------------------------------------
# main() — wholeness filter + excluded-systems split + two-file output
# ---------------------------------------------------------------------------


def _run_validate(
    monkeypatch,
    tmp_dir,
    msf_rows,
    *,
    wholeness_threshold=0.8,
    excluded_systems="Flagellum,Tad,T3SS",
):
    msf_dir = os.path.join(tmp_dir, "msf")
    os.makedirs(msf_dir, exist_ok=True)
    _write_best_solution(os.path.join(msf_dir, "best_solution.tsv"), msf_rows)

    gene_info = os.path.join(tmp_dir, "gene_info.tsv")
    with open(gene_info, "w") as f:
        f.write("locus_tag\tcontig\tstart\tend\n")  # required arg, content unused

    out_components = os.path.join(tmp_dir, "ss_components.tsv")
    out_systems = os.path.join(tmp_dir, "valid_systems.tsv")
    run_script_main(
        monkeypatch,
        validate_main,
        [
            "validate_macsyfinder_systems",
            "--msf-dir",
            msf_dir,
            "--gene-info",
            gene_info,
            "--sample",
            "test_sample",
            "--wholeness-threshold",
            str(wholeness_threshold),
            "--excluded-systems",
            excluded_systems,
            "--out-components",
            out_components,
            "--out-systems",
            out_systems,
        ],
    )
    return read_tsv_rows(out_components), read_tsv_rows(out_systems)


class TestMainEndToEnd:
    def test_wholeness_filter_drops_low_systems(self, monkeypatch, tmp_dir):
        rows = [
            _component("good_T2SS_1", "GENE_A", wholeness=0.95),
            _component("weak_T2SS_2", "GENE_B", wholeness=0.5),
        ]
        _, systems = _run_validate(monkeypatch, tmp_dir, rows)
        assert {s["sys_id"] for s in systems} == {"good_T2SS_1"}

    def test_excluded_systems_marked_but_kept(self, monkeypatch, tmp_dir):
        # Excluded systems still appear in BOTH outputs but with excluded=True
        rows = [
            _component("contig_T2SS_1", "GENE_A", model_fqn="TXSScan/bacteria/diderm/T2SS"),
            _component("contig_Flagellum_1", "GENE_F", model_fqn="TXSScan/bacteria/diderm/Flagellum"),
        ]
        components, systems = _run_validate(monkeypatch, tmp_dir, rows)
        excluded_flag = {s["sys_id"]: s["excluded"] for s in systems}
        assert excluded_flag["contig_T2SS_1"] == "False"
        assert excluded_flag["contig_Flagellum_1"] == "True"
        # Both still appear in component detail (audit trail)
        assert {c["sys_id"] for c in components} == {
            "contig_T2SS_1",
            "contig_Flagellum_1",
        }

    def test_n_components_correct(self, monkeypatch, tmp_dir):
        rows = [
            _component("contig_T2SS_1", "GENE_A", "gspD", model_fqn="TXSScan/bacteria/diderm/T2SS"),
            _component("contig_T2SS_1", "GENE_B", "gspE", model_fqn="TXSScan/bacteria/diderm/T2SS"),
            _component("contig_T2SS_1", "GENE_C", "gspF", model_fqn="TXSScan/bacteria/diderm/T2SS"),
        ]
        _, systems = _run_validate(monkeypatch, tmp_dir, rows)
        assert systems[0]["n_components"] == "3"

    def test_components_carry_sample_id(self, monkeypatch, tmp_dir):
        rows = [_component("contig_T2SS_1", "GENE_A", model_fqn="TXSScan/bacteria/diderm/T2SS")]
        components, _ = _run_validate(monkeypatch, tmp_dir, rows)
        assert all(c["sample_id"] == "test_sample" for c in components)

    def test_custom_excluded_systems(self, monkeypatch, tmp_dir):
        # User passes --excluded-systems="" → nothing excluded → flagellum kept
        rows = [_component("contig_Flagellum_1", "GENE_F", model_fqn="TXSScan/bacteria/diderm/Flagellum")]
        _, systems = _run_validate(
            monkeypatch,
            tmp_dir,
            rows,
            excluded_systems="",
        )
        assert systems[0]["excluded"] == "False"

    def test_no_systems_writes_header_only(self, monkeypatch, tmp_dir):
        components, systems = _run_validate(monkeypatch, tmp_dir, [])
        assert components == []
        assert systems == []
        # Header still present
        with open(os.path.join(tmp_dir, "valid_systems.tsv")) as f:
            assert f.readline().strip()
